---


- name: install deps
  sudo: yes
  apt:
    name='{{item}}'
    state=installed
    update_cache=yes
    cache_valid_time=3600
    force=yes
  with_items:
    - libboost1.55-all-dev
    - libaio-dev
    - ninja-build
    - ragel
    - libhwloc-dev
    - libnuma-dev
    - libpciaccess-dev
    - libcrypto++-dev
    - libxen-dev
    - libxml2-dev
    - xfslibs-dev
    - libgnutls28-dev

- name: Sync soure from git
  git:
    repo='https://github.com/scylladb/seastar.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/seastar'
    update=yes
    recursive=yes
    version='cf1716f'
    force=yes

# Does not support  --prefix="{{third_party_dir}}"
# Does not support ccache either. oiiiiiiiiiii
- command: ./configure.py --enable-dpdk --compiler=g++-5
  args:
    chdir: '{{goobly_cache_dir}}/seastar'
    creates: '{{goobly_cache_dir}}/seastar/build.ninja'

# does not support install
- command: ninja
  args:
    chdir: '{{goobly_cache_dir}}/seastar'
    creates: '{{goobly_cache_dir}}/seastar/build/release/libseastar.a'

- name: copy main seastar.a lib
  copy:
    src='{{goobly_cache_dir}}/seastar/build/release/libseastar.a'
    dest="{{third_party_dir}}/lib/libseastar.a"

- name: copy all the libseastar dpdk includes
  copy:
    src='{{goobly_cache_dir}}/seastar/build/dpdk/lib/{{item}}'
    dest="{{third_party_dir}}/lib/{{item}}"
  with_items:
    - libethdev.a
    - librte_kvargs.a
    - librte_pmd_cxgbe.a
    - librte_pmd_ixgbe.a
    - librte_ring.a
    - librte_cfgfile.a
    - librte_malloc.a
    - librte_pmd_e1000.a
    - librte_pmd_null.a
    - librte_timer.a
    - librte_cmdline.a
    - librte_mbuf.a
    - librte_pmd_enic.a
    - librte_pmd_ring.a
    - librte_vhost.a
    - librte_eal.a
    - librte_mempool.a
    - librte_pmd_fm10k.a
    - librte_pmd_virtio.a
    - librte_hash.a
    - librte_pmd_af_packet.a
    - librte_pmd_i40e.a
    - librte_pmd_vmxnet3_uio.a

- name: copy all the libseastar dpdk includes
  copy:
    src='{{goobly_cache_dir}}/seastar/build/dpdk/include/'
    dest="{{third_party_dir}}/include/dpdk/"

- name: make sure the directories exist for headers of seastar
  file:
    state=directory
    path="{{third_party_dir}}/include/seastar/{{item}}"
  with_items:
    - core
    - http
    - net
    - rpc
    - apps
    - http
    - 'apps/memcached'
    - util
    - 'core/xen'
    - json

- name: copy all the seastar headers
  copy:
    src='{{goobly_cache_dir}}/seastar/{{item}}'
    dest="{{third_party_dir}}/include/seastar/{{item}}"
  with_items:
    - core/task.hh
    - core/shared_ptr_debug_helper.hh
    - core/unaligned.hh
    - core/vla.hh
    - core/future.hh
    - core/future-util.hh
    - core/do_with.hh
    - core/bitops.hh
    - core/units.hh
    - core/shared_ptr.hh
    - core/gate.hh
    - core/file.hh
    - core/dpdk_rte.hh
    - core/fstream.hh
    - core/temporary_buffer.hh
    - core/sharded.hh
    - core/apply.hh
    - core/circular_buffer.hh
    - core/scollectd.hh
    - core/posix.hh
    - core/vector-data-sink.hh
    - core/bitset-iter.hh
    - core/app-template.hh
    - core/simple-stream.hh
    - core/iostream-impl.hh
    - core/queue.hh
    - core/shared_future.hh
    - core/sstring.hh
    - core/memory.hh
    - core/xen/gntalloc.hh
    - core/xen/evtchn.hh
    - core/xen/osv_xen.hh
    - core/xen/xenstore.hh
    - core/systemwide_memory_barrier.hh
    - core/shared_mutex.hh
    - core/prefetch.hh
    - core/rwlock.hh
    - core/pipe.hh
    - core/reactor.hh
    - core/enum.hh
    - core/print.hh
    - core/array_map.hh
    - core/iostream.hh
    - core/stream.hh
    - core/function_traits.hh
    - core/fair_queue.hh
    - core/resource.hh
    - core/distributed.hh
    - core/timer-set.hh
    - core/timer.hh
    - core/scattered_message.hh
    - core/transfer.hh
    - core/deleter.hh
    - core/byteorder.hh
    - core/scollectd_api.hh
    - core/semaphore.hh
    - core/ragel.hh
    - core/thread.hh
    - core/seastar.hh
    - core/align.hh
    - core/sleep.hh
    - json/json_elements.hh
    - json/formatter.hh
    - util/transform_iterator.hh
    - util/defer.hh
    - util/eclipse.hh
    - util/function_input_iterator.hh
    - util/is_smart_ptr.hh
    - util/conversions.hh
    - http/json_path.hh
    - http/file_handler.hh
    - http/matchrules.hh
    - http/reply.hh
    - http/routes.hh
    - http/matcher.hh
    - http/mime_types.hh
    - http/common.hh
    - http/handlers.hh
    - http/api_docs.hh
    - http/exception.hh
    - http/request.hh
    - http/transformers.hh
    - http/httpd.hh
    - http/function_handlers.hh
    - apps/memcached/memcached.hh
    - net/const.hh
    - net/arp.hh
    - net/native-stack-impl.hh
    - net/posix-stack.hh
    - net/net.hh
    - net/ethernet.hh
    - net/toeplitz.hh
    - net/dpdk.hh
    - net/proxy.hh
    - net/tls.hh
    - net/virtio.hh
    - net/udp.hh
    - net/virtio-interface.hh
    - net/dhcp.hh
    - net/tcp.hh
    - net/stack.hh
    - net/api.hh
    - net/packet.hh
    - net/packet-util.hh
    - net/ip.hh
    - net/xenfront.hh
    - net/packet-data-source.hh
    - net/native-stack.hh
    - net/byteorder.hh
    - net/tcp-stack.hh
    - net/ip_checksum.hh
    - rpc/rpc.hh
    - rpc/rpc_types.hh
    - rpc/rpc_impl.hh
